#!/bin/sh

#######################################################################################
# convert and upload (flash) random picture to ESP with Eastrising colour TFT display #
# for now only Eastrising display, also only slot #0.                                 #
# it uses ImageMagick ("convert") for the conversion.                                 #
#######################################################################################

if [ $# != 3 ]; then
	echo "usage: $0: <host> <slot> <image>"
	exit 1
fi

case $2 in
	0)
		offset=0x200000
		;;
	1)
		offset=0x280000
		;;
	*)
		echo "$0: use slot 0 or slot 1"
		exit 1
		;;
esac

tmpfile="$(mktemp --suffix=.ppm)"

trap 'rm -f "$tmpfile"' 0

convert -resize '480x272!' -gamma 0.6 -depth 8 "$3" "ppm:$tmpfile"
espflash --write  --host "$1" --start $offset --file "$tmpfile"
espflash --verify --host "$1" --start $offset --file "$tmpfile"
